[package]
name = "x9"
version = "0.1.0"
edition = "2021"


[lib]
name  = "x9"
path = "src/lib.rs"

[[bin]]
name  = "x9"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.85"
im = "15.1.0"
bigdecimal = "0.4.3"
once_cell = "1.4.0"
parking_lot = "0.12.3"
rand = "0.8.5"
