[package]
name = "x9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name  = "x9"
path = "src/lib.rs"

[[bin]]
name  = "x9"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.85"
im = "15.1.0"
bigdecimal = "0.4.3"